<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="1110_LLMChat\**" />
    <EmbeddedResource Remove="1110_LLMChat\**" />
    <None Remove="1110_LLMChat\**" />
    <Page Remove="1110_LLMChat\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VPet-Simulator.Windows.Interface" Version="1.1.0.66" />
  </ItemGroup>
</Project>
